### ISSUE TITLE
timestamp is missing a -

### ISSUE THREAD

**Issue by katrinleinweber** [ropensci/jaod#10]
I'm seeing this for any DOI search I conduct:

```r
> jaod::jaod_article_search("doi:10.3389/fphar.2019.00841")
$timestamp
[1] "2019-0827T07:23:16Z"
```

It should be `...08-27...` to be [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601). Not sure if this error is delivered by DOAJ or introduced somewhere here. Does anyone know more? cc @Steven-Eardley

**Comment by Steven-Eardley** [comment]
@katrinleinweber That's a bug on our end, sorry!

https://github.com/DOAJ/doaj/blob/master/portality/api/v1/discovery.py#L246

```python
# build the response object
        result = {
            "total" : total,
            "page" : page,
            "pageSize" : page_size,
            "timestamp" : datetime.utcnow().strftime("%Y-%m%dT%H:%M:%SZ"),
            "query" : q,
            "results" : obs
        }
```
I'll get a fix in for it shortly.

**Comment by sckott** [comment]
thanks for the issue @katrinleinweber  and for the quick reply @Steven-Eardley - Will look out for a fix in the API

**Comment by sckott** [comment]
@katrinleinweber  looks like that issue is resolved on their end, does the timestamp look good now?

**Comment by katrinleinweber** [comment]
It does 8601% :-D

**Comment by sckott** [comment]
@katrinleinweber fyi, new version on cran now
