### ISSUE TITLE
Parameter sort seems to have no effect in jaod_article_search

### ISSUE THREAD

**Issue by pkraker** [ropensci/jaod#3]
Both of these queries give the desired result (sort by year) when accessing the API directly, but not when using jaod_article_search:

`jaod_article_search(query="green", sort="year:desc")`
`jaod_article_search(query="green", sort="bibjson.year:desc")`

**Comment by sckott** [comment]
thanks for the report @pkraker 

will have a look

**Comment by sckott** [comment]
woopsy! I wasn't capturing the `sort` parameter internally in the function. fixing now

**Comment by sckott** [comment]
@pkraker okay, reinstall

**Comment by pkraker** [comment]
Works like a charm, thanks!
