### ISSUE TITLE
Always returns error 403

### ISSUE THREAD

**Issue by ebbertd** [ropensci/jaod#6]
No matter which request I make it always returns error 403, same reason why the travis builds are failing.

**Comment by sckott** [comment]
huh, looks like they introduced authentication. will push a fix soon

**Comment by sckott** [comment]
i'ved asked a question here https://groups.google.com/forum/#!topic/doaj-public-api/GiKfNxlGI2E

**Comment by sckott** [comment]
@ebbertd  still waiting to hear back from them ⏲

**Comment by sckott** [comment]
Seems like its back up and working now, can you try it again @ebbertd

**Comment by ebbertd** [comment]
It works now. Thanks!

**Comment by dommitchell** [comment]
Hi! We had a major DDOS issue which we resolved last week. Changes (one of which was authentication) which we made to mitigate future DDOS attacks. We're still working through unwanted outcomes of those changes but overall stability was improved.

Let me know if you experience issues again. Thanks, Dom, DOAJ Operations Manager

**Comment by sckott** [comment]
thanks @dommitchell - totally understand and thanks for the quick fix.
